"""Orchestrates all file creation for the scaffolded project."""

from __future__ import annotations

import shutil
from pathlib import Path

from rich.console import Console
from rich.tree import Tree

from proj_toolkit.claude_md import render_claude_md
from proj_toolkit.config import BackendFramework, ProjectConfig, get_backend_plugin, get_frontend_plugin
from proj_toolkit.skills import generate_skills

# Ensure plugins are registered by importing them
import proj_toolkit.frameworks.frontend.react  # noqa: F401
import proj_toolkit.frameworks.backend.django  # noqa: F401
import proj_toolkit.frameworks.backend.fastapi  # noqa: F401
import proj_toolkit.frameworks.backend.node  # noqa: F401

console = Console()


def scaffold(config: ProjectConfig, target_dir: Path) -> None:
    """Generate the full project structure into *target_dir*."""
    frontend_plugin = get_frontend_plugin(config.frontend_framework.value)
    backend_plugin = get_backend_plugin(config.backend_framework.value)

    _write_frontend(config, frontend_plugin, target_dir)
    _write_backend(config, backend_plugin, target_dir)
    _write_claude_dir(config, target_dir)
    _write_claude_md(config, frontend_plugin, backend_plugin, target_dir)
    _write_dockerfiles(config, frontend_plugin, backend_plugin, target_dir)
    _write_skills(config, target_dir)

    _print_tree(target_dir)


def _write_frontend(config: ProjectConfig, plugin, target_dir: Path) -> None:
    base = target_dir / "frontend"
    files = plugin.generate_files(config.frontend_language, config.project_name)
    for spec in files:
        dest = base / spec.relative_path
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(spec.content, encoding="utf-8")
    console.print(f"[green]✓[/green] frontend/ ({len(files)} files)")


def _write_backend(config: ProjectConfig, plugin, target_dir: Path) -> None:
    base = target_dir / "backend"
    files = plugin.generate_files(config.backend_language, config.project_name)
    for spec in files:
        dest = base / spec.relative_path
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(spec.content, encoding="utf-8")
    console.print(f"[green]✓[/green] backend/ ({len(files)} files)")


def _write_claude_dir(config: ProjectConfig, target_dir: Path) -> None:
    claude_dir = target_dir / "claude"
    claude_dir.mkdir(exist_ok=True)

    # prd.md — copy from user-provided path
    prd_src = Path(config.prd_path)
    prd_dest = claude_dir / "prd.md"
    shutil.copy2(prd_src, prd_dest)

    # context.md
    (claude_dir / "context.md").write_text(
        _render_context(config), encoding="utf-8"
    )

    # tasks/ and decisions/ with .gitkeep
    for subdir in ("tasks", "decisions"):
        d = claude_dir / subdir
        d.mkdir(exist_ok=True)
        (d / ".gitkeep").touch()

    # AGENTS.md
    (claude_dir / "AGENTS.md").write_text(
        _render_agents_md(config), encoding="utf-8"
    )

    console.print("[green]✓[/green] claude/ (prd.md, context.md, AGENTS.md, tasks/, decisions/)")


def _write_claude_md(config, frontend_plugin, backend_plugin, target_dir: Path) -> None:
    content = render_claude_md(config, frontend_plugin, backend_plugin)
    (target_dir / "CLAUDE.md").write_text(content, encoding="utf-8")
    console.print("[green]✓[/green] CLAUDE.md")


def _render_context(config: ProjectConfig) -> str:
    return f"""\
# Project Context

Auto-generated by proj-toolkit.

## Configuration

| Field              | Value                        |
|--------------------|------------------------------|
| project_name       | {config.project_name}        |
| frontend_framework | {config.frontend_framework.value} |
| frontend_language  | {config.frontend_language.value}  |
| backend_framework  | {config.backend_framework.value}  |
| backend_language   | {config.backend_language.value}   |
| prd_path           | claude/prd.md                |

## Paths

- Frontend source: `frontend/src/`
- Backend source: `backend/`
- PRD: `claude/prd.md`
- Tasks: `claude/tasks/`
- Decisions: `claude/decisions/`
"""


def _render_agents_md(config: ProjectConfig) -> str:
    return f"""\
# AGENTS.md — Multi-Agent Coordination for {config.project_name}

## Principles

1. **One agent, one concern**: Frontend agents work in `frontend/`, backend agents in `backend/`.
2. **Read context.md first**: Always read `claude/context.md` before starting work.
3. **Task files are locks**: Before starting a task, create a file in `claude/tasks/` named
   after your task (e.g., `claude/tasks/implement-auth.md`). Check for existing files first.
4. **Decisions go in decisions/**: Record significant architecture choices in `claude/decisions/`
   as `YYYY-MM-DD-short-title.md`.
5. **No cross-boundary writes**: A frontend agent must not modify backend files and vice versa.
   Route cross-boundary changes through a coordinating agent.

## Workflow

1. Read `claude/prd.md` and `claude/context.md`
2. Check `claude/tasks/` for in-progress work
3. Create your task file
4. Implement changes within your boundary
5. Update CLAUDE.md if the architecture changes
6. Delete your task file when done

## Boundaries

| Agent type    | May write to                    |
|---------------|---------------------------------|
| frontend      | `frontend/`                     |
| backend       | `backend/`                      |
| infra         | Root config files               |
| coordinator   | `claude/`, `CLAUDE.md`          |
"""


def _write_dockerfiles(config: ProjectConfig, frontend_plugin, backend_plugin, target_dir: Path) -> None:
    # frontend/Dockerfile
    (target_dir / "frontend" / "Dockerfile").write_text(
        frontend_plugin.dockerfile_content(config.frontend_language, config.project_name),
        encoding="utf-8",
    )

    # backend/Dockerfile
    (target_dir / "backend" / "Dockerfile").write_text(
        backend_plugin.dockerfile_content(config.backend_language, config.project_name),
        encoding="utf-8",
    )

    # root docker-compose.yml
    backend_port = 3000 if config.backend_framework == BackendFramework.NODE else 8000
    env_file_line = "    env_file:\n      - ./backend/.env\n" if (target_dir / "backend" / ".env.example").exists() else ""
    compose = f"""\
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "{backend_port}:{backend_port}"
{env_file_line}"""
    (target_dir / "docker-compose.yml").write_text(compose, encoding="utf-8")

    console.print("[green]✓[/green] Dockerfiles (frontend/Dockerfile, backend/Dockerfile, docker-compose.yml)")


def _write_skills(config: ProjectConfig, target_dir: Path) -> None:
    commands_dir = target_dir / ".claude" / "commands"
    commands_dir.mkdir(parents=True, exist_ok=True)

    skills = generate_skills(config)
    for skill in skills:
        (commands_dir / f"{skill.name}.md").write_text(skill.content, encoding="utf-8")

    names = ", ".join(f"/{s.name}" for s in skills)
    console.print(f"[green]✓[/green] .claude/commands/ ({names})")


def _print_tree(target_dir: Path) -> None:
    tree = Tree(f"[bold]{target_dir.name or '.'}[/bold]")
    for top in sorted(target_dir.iterdir()):
        if top.is_dir():
            branch = tree.add(f"[cyan]{top.name}/[/cyan]")
            for child in sorted(top.iterdir()):
                if child.is_dir():
                    branch.add(f"[cyan]{child.name}/[/cyan]")
                else:
                    branch.add(child.name)
        else:
            tree.add(top.name)
    console.print(tree)
